#line 2 "wizard_protocol_lexer.c"

#line 4 "wizard_protocol_lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer wizard_create_buffer
#define yy_delete_buffer wizard_delete_buffer
#define yy_flex_debug wizard_flex_debug
#define yy_init_buffer wizard_init_buffer
#define yy_flush_buffer wizard_flush_buffer
#define yy_load_buffer_state wizard_load_buffer_state
#define yy_switch_to_buffer wizard_switch_to_buffer
#define yyin wizardin
#define yyleng wizardleng
#define yylex wizardlex
#define yylineno wizardlineno
#define yyout wizardout
#define yyrestart wizardrestart
#define yytext wizardtext
#define yywrap wizardwrap
#define yyalloc wizardalloc
#define yyrealloc wizardrealloc
#define yyfree wizardfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE wizardrestart(wizardin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int wizardleng;

extern FILE *wizardin, *wizardout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up wizardtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up wizardtext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via wizardrestart()), so that the user can continue scanning by
	 * just pointing wizardin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when wizardtext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int wizardleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow wizardwrap()'s to do buffer switches
 * instead of setting up a fresh wizardin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void wizardrestart (FILE *input_file  );
void wizard_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE wizard_create_buffer (FILE *file,int size  );
void wizard_delete_buffer (YY_BUFFER_STATE b  );
void wizard_flush_buffer (YY_BUFFER_STATE b  );
void wizardpush_buffer_state (YY_BUFFER_STATE new_buffer  );
void wizardpop_buffer_state (void );

static void wizardensure_buffer_stack (void );
static void wizard_load_buffer_state (void );
static void wizard_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER wizard_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE wizard_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE wizard_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE wizard_scan_bytes (yyconst char *bytes,int len  );

void *wizardalloc (yy_size_t  );
void *wizardrealloc (void *,yy_size_t  );
void wizardfree (void *  );

#define yy_new_buffer wizard_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        wizardensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            wizard_create_buffer(wizardin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        wizardensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            wizard_create_buffer(wizardin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define wizardwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *wizardin = (FILE *) 0, *wizardout = (FILE *) 0;

typedef int yy_state_type;

extern int wizardlineno;

int wizardlineno = 1;

extern char *wizardtext;
#define yytext_ptr wizardtext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up wizardtext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	wizardleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 11
#define YY_END_OF_BUFFER 12
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[196] =
    {   0,
        0,    0,    0,    0,    0,    0,   12,   10,    6,    8,
        9,   10,   10,    8,    4,    5,   11,    2,   10,    3,
       10,    8,    9,    0,    8,    0,    3,    0,    1,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    7,    0,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,

        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    0

    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    1,    3,    4,
        1,    1,    5,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    6,    1,    1,
        1,    7,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    8,    3,    3,    3,    9,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,   10,   10,   10,   10,   10,   10,
       11,   10,   10,   10,   10,   10,   10,   10,   10,   10,
       10,   10,   12,   10,   10,   10,   10,   10,   10,   10,
        3,    3,    3,    3,    3,    3,   13,   10,   14,   15,

       16,   17,   18,   19,   20,   21,   10,   10,   22,   23,
       24,   10,   10,   25,   26,   27,   28,   29,   10,   10,
       30,   10,    3,    3,    3,    3,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,   31,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   32,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[33] =
    {   0,
        1,    1,    2,    3,    3,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[203] =
    {   0,
        0,   32,   64,   96,  128,  160,  449,  532,  532,    0,
      532,  439,  422,  420,  532,  532,  532,  532,    4,  532,
      418,    0,  532,  409,  413,    6,  532,  409,  532,    0,
      397,    5,    6,   11,    7,   14,    8,   15,  392,   18,
       20,  186,   36,   22,   37,  387,   38,   48,   31,   49,
       45,   69,  384,   53,   71,    1,   83,  383,  100,   85,
       36,   72,   73,   76,   77,  102,  107,  376,  104,  103,
      100,  105,  115,  116,  111,  113,  118,  128,  139,  132,
      140,  143,  375,  144,  532,  364,  208,  136,  140,  165,
      170,  179,  149,  358,  183,  199,  175,   35,  192,  213,

      217,  150,  348,  209,  189,  216,  218,  242,  246,  166,
      250,  308,  237,  327,  245,  246,  268,  313,  273,  277,
      305,  218,  264,  287,  294,  272,  299,  307,  289,  289,
      296,  304,  311,  161,  312,  319,  338,  209,  342,  346,
      273,  254,  336,  335,  345,  185,  352,  353,  360,  225,
      367,  368,  376,  245,  381,  384,  403,  279,  407,   73,
      237,  406,  412,  241,   66,  281,  405,  164,  413,  293,
      421,  352,  440,  298,   67,  332,  416,  429,  448,   57,
      439,  458,   40,  451,  448,  459,  460,  467,  468,  476,
      479,  484,  492,  493,  532,  518,  521,  524,   15,  526,

        1,  528
    } ;

static yyconst flex_int16_t yy_def[203] =
    {   0,
      196,  196,  197,  197,  198,  198,  195,  195,  195,  199,
      195,  195,  195,  199,  195,  195,  195,  195,  200,  195,
      195,  199,  195,  195,  199,  200,  195,  195,  195,  201,
      201,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      201,  201,  201,  201,  201,  201,  201,  201,   42,  201,
      201,  201,  201,  201,  201,   42,  201,  201,  201,  201,
       42,  201,  201,  201,  201,  201,  201,  201,  201,  201,
       42,  201,  201,  201,  201,  201,  201,  201,  201,  201,
      202,  201,  201,  202,  195,  195,  202,  201,   42,  202,
      202,  202,  201,  201,  202,  202,  202,   42,  202,  202,

      202,  201,   87,   87,   87,  201,   87,  202,  202,  201,
      202,   87,   87,  201,   87,   87,  202,   42,  202,  202,
       87,  201,   87,  202,  202,  201,  202,   87,   87,  201,
       87,   87,   87,   42,   87,   87,  202,  201,  202,  202,
       87,  201,   87,   87,   87,   42,   87,   87,   87,  201,
       87,   87,   87,  201,   87,   87,  202,  201,  202,   87,
      201,   87,  202,  201,   87,  201,   87,  201,   87,  201,
       87,  201,  202,  201,   87,  201,   87,   87,  202,   87,
       87,  202,   87,   87,   87,   87,   87,   87,   87,   87,
       87,   87,   87,   87,    0,  195,  195,  195,  195,  195,

      195,  195
    } ;

static yyconst flex_int16_t yy_nxt[565] =
    {   0,
        8,    9,   31,   11,   12,   13,   14,   27,   28,   27,
       28,   32,   32,   32,   32,   31,   22,   32,   36,   59,
       32,   32,   38,   33,   32,   34,   32,   40,   32,   35,
       15,   16,    8,    9,   37,   11,   12,   13,   14,   39,
       43,   41,   32,   32,   32,   31,   47,   44,   64,   31,
       31,   32,  184,  102,   32,   32,   48,   52,   54,   32,
       50,   46,   15,   16,    8,    8,    8,   17,    8,   13,
        8,    8,    8,   51,   53,   32,   57,   32,   32,   32,
      181,  177,   32,   32,  167,  163,   58,   55,   66,   32,
       67,   32,   68,   65,    8,    8,    8,    8,    8,   17,

        8,   13,    8,    8,    8,   60,   32,   63,   32,   32,
       32,   32,   36,   32,   31,   69,   74,   32,   73,   32,
       75,   32,   32,   62,   32,   78,    8,    8,    8,    8,
       72,   20,   21,   13,   32,   70,   81,   76,   32,   79,
       77,   80,   32,   85,   86,   32,   87,   85,   86,   32,
       87,   93,   94,   83,   31,   32,   32,   81,    8,    8,
        8,    8,  106,   20,   21,   13,   82,   88,   85,   86,
       32,   87,   32,   85,   86,   31,   87,   95,   85,   86,
      114,   87,   85,   86,  138,   87,   85,   86,  170,   87,
        8,    8,   32,   96,   97,   85,   86,  150,  103,   31,

       45,  101,   85,   86,   33,   87,   34,   84,   99,   84,
       35,   85,   86,  109,   87,   32,   85,   86,  100,   87,
       85,   86,   32,   87,   32,  142,   90,   84,   91,   84,
      126,   32,   92,   84,  108,  104,   84,  111,   84,  154,
      110,   39,   84,   32,  105,   85,   86,   32,  112,   85,
       86,   32,   87,   85,   86,   84,   87,   84,  119,  164,
      146,   84,  117,   84,  120,   84,   84,  166,  113,   84,
       84,   85,   86,  158,  121,  115,   85,   86,   32,   87,
       85,   86,   84,   87,   84,   32,  127,   32,   84,  145,
       85,   86,  124,  128,  161,  134,  123,   85,   86,   32,

       87,  130,   85,   86,   32,   87,   95,   84,  168,   84,
      133,  135,  172,   84,   84,  176,   84,  129,  136,  132,
       84,  131,   84,  125,   84,  139,  137,  122,   84,   84,
       84,   84,   84,  118,  116,   84,   84,   84,   32,   84,
       81,   85,   86,   84,  141,   85,   86,  140,   87,   85,
       86,  147,   87,   84,   84,   84,   84,  148,   32,   84,
       84,  144,  107,   84,   98,   84,  151,   85,  143,  149,
       84,   84,   84,   84,  174,  155,   84,   84,   84,  152,
       84,   89,   71,  153,   84,   84,   84,   84,   84,   61,
       56,   84,   84,   49,   84,  156,   84,  157,   42,   84,

       84,   84,   84,   32,   84,   84,   85,   86,  159,  160,
       85,   86,   27,   87,  155,   85,   86,  169,  165,   30,
       29,   27,  162,   84,   84,   84,   84,   25,  178,   84,
       84,   84,   24,   84,   84,  173,   84,  171,   99,   84,
       84,   84,   23,   85,   86,   84,  175,   84,  195,   84,
      195,   85,   86,   84,  180,  182,  195,   84,  179,   84,
      195,   85,   86,   84,  183,  185,   84,  195,   84,   84,
      195,   84,   84,  195,  187,   84,  186,   84,   84,   84,
       84,  195,  188,   84,   84,   84,   84,   84,   84,  195,
      195,   84,   84,  189,   84,  190,   84,   84,  192,   84,

      191,  155,   84,   84,   84,  195,  193,  195,   84,  194,
       84,   84,   84,   84,  195,  195,   84,   84,   10,   10,
       10,   18,   18,   18,   19,   19,   19,   26,   26,   84,
       84,    7,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195
    } ;

static yyconst flex_int16_t yy_chk[565] =
    {   0,
        1,    1,  201,    1,    1,    1,    1,   19,   19,   26,
       26,   32,   33,   35,   37,   56,  199,   34,   33,   56,
       36,   38,   35,   32,   40,   32,   41,   37,   44,   32,
        1,    1,    2,    2,   34,    2,    2,    2,    2,   36,
       40,   38,   43,   45,   47,   49,   44,   41,   61,   98,
       61,   51,  183,   98,   48,   50,   45,   49,   51,   54,
       47,   43,    2,    2,    3,    3,    3,    3,    3,    3,
        3,    3,    3,   48,   50,   52,   54,   55,   62,   63,
      180,  175,   64,   65,  165,  160,   55,   52,   63,   57,
       64,   60,   65,   62,    3,    3,    4,    4,    4,    4,

        4,    4,    4,    4,    4,   57,   59,   60,   66,   70,
       69,   72,   59,   67,   71,   66,   71,   75,   70,   76,
       72,   73,   74,   59,   77,   75,    4,    4,    5,    5,
       69,    5,    5,    5,   78,   67,   78,   73,   80,   76,
       74,   77,   88,   81,   81,   79,   81,   84,   84,   82,
       84,   88,   89,   80,   89,   93,  102,   93,    5,    5,
        6,    6,  102,    6,    6,    6,   79,   82,   90,   90,
      168,   90,  110,   91,   91,  134,   91,   90,   97,   97,
      110,   97,   92,   92,  134,   92,   95,   95,  168,   95,
        6,    6,   42,   91,   92,   99,   99,  146,   99,  146,

       42,   97,   96,   96,   42,   96,   42,  105,   95,  105,
       42,   87,   87,  105,   87,  138,  100,  100,   96,  100,
      101,  101,  106,  101,  122,  138,   87,  104,   87,  104,
      122,  150,   87,  104,  104,  100,  107,  107,  107,  150,
      106,  106,  107,  161,  101,  108,  108,  164,  108,  109,
      109,  154,  109,  111,  111,  113,  111,  113,  115,  161,
      142,  113,  113,  115,  116,  115,  116,  164,  109,  115,
      116,  117,  117,  154,  117,  111,  119,  119,  126,  119,
      120,  120,  123,  120,  123,  158,  123,  166,  123,  141,
      124,  124,  120,  124,  158,  130,  119,  125,  125,  170,

      125,  126,  127,  127,  174,  127,  125,  129,  166,  129,
      129,  131,  170,  129,  131,  174,  131,  125,  132,  128,
      131,  127,  132,  121,  132,  135,  133,  118,  132,  133,
      135,  133,  135,  114,  112,  133,  135,  136,  176,  136,
      176,  137,  137,  136,  137,  139,  139,  136,  139,  140,
      140,  143,  140,  144,  143,  144,  143,  144,  172,  144,
      143,  140,  103,  145,   94,  145,  147,   86,  139,  145,
      147,  148,  147,  148,  172,  151,  147,  148,  149,  148,
      149,   83,   68,  149,  149,  151,  152,  151,  152,   58,
       53,  151,  152,   46,  153,  152,  153,  153,   39,  155,

      153,  155,  156,   31,  156,  155,  157,  157,  156,  157,
      159,  159,   28,  159,  162,  163,  163,  167,  163,   25,
       24,   21,  159,  167,  162,  167,  162,   14,  177,  167,
      162,  169,   13,  169,  177,  171,  177,  169,  169,  171,
      177,  171,   12,  173,  173,  171,  173,  178,    7,  178,
        0,  179,  179,  178,  179,  181,    0,  181,  178,  181,
        0,  182,  182,  181,  182,  184,  185,    0,  185,  184,
        0,  184,  185,    0,  186,  184,  185,  186,  187,  186,
      187,    0,  187,  186,  187,  188,  189,  188,  189,    0,
        0,  188,  189,  188,  190,  189,  190,  191,  191,  191,

      190,  194,  192,  191,  192,    0,  192,    0,  192,  193,
      193,  194,  193,  194,    0,    0,  193,  194,  196,  196,
      196,  197,  197,  197,  198,  198,  198,  200,  200,  202,
      202,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195,  195,  195,  195,  195,  195,  195,
      195,  195,  195,  195
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int wizard_flex_debug;
int wizard_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *wizardtext;
#line 1 "wizard_protocol_lexer.l"
#line 2 "wizard_protocol_lexer.l"
/* Warlock Front End
 * Copyright 2005 Sean Proctor, Marshall Culpepper
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <string.h>
#include <ctype.h>

#include <gtk/gtk.h>
#include <glade/glade.h>

#include "highlight.h"
#include "debug.h"
#include "warlock.h"
#include "warlockstring.h"
#include "compass.h"
#include "hand.h"
#include "warlocktime.h"
#include "status.h"
#include "warlockview.h"
#include "script.h"
#include "simu_connection.h"

#ifdef CONFIG_SPIDERMONKEY
#include "jsscript.h"
#endif

/* external global variables */
extern SimuConnection *connection;
extern GladeXML *warlock_xml;
extern gboolean prompting;

/* local variables */
static gboolean highlighting = FALSE;
static gboolean familiar = FALSE;
static gboolean room_title = FALSE;
static gboolean death = FALSE;
static char command = 0;
static gboolean quit = FALSE;

/* local function definitions */
static char *lexer_string (void);
static void handle_command (char command, char *params);
static void arrival_string (void);
static void output_string (void);
static void eol_code (void);
static char *parse_hand (char *str);
static void unhandled_character (void);
#define YY_NO_INPUT 1

#line 739 "wizard_protocol_lexer.c"

#define INITIAL 0
#define COMMAND 1
#define PARAMS 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int wizardlex_destroy (void );

int wizardget_debug (void );

void wizardset_debug (int debug_flag  );

YY_EXTRA_TYPE wizardget_extra (void );

void wizardset_extra (YY_EXTRA_TYPE user_defined  );

FILE *wizardget_in (void );

void wizardset_in  (FILE * in_str  );

FILE *wizardget_out (void );

void wizardset_out  (FILE * out_str  );

int wizardget_leng (void );

char *wizardget_text (void );

int wizardget_lineno (void );

void wizardset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int wizardwrap (void );
#else
extern int wizardwrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( wizardtext, wizardleng, 1, wizardout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( wizardin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( wizardin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, wizardin))==0 && ferror(wizardin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(wizardin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int wizardlex (void);

#define YY_DECL int wizardlex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after wizardtext and wizardleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 75 "wizard_protocol_lexer.l"

#line 928 "wizard_protocol_lexer.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! wizardin )
			wizardin = stdin;

		if ( ! wizardout )
			wizardout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			wizardensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				wizard_create_buffer(wizardin,YY_BUF_SIZE );
		}

		wizard_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of wizardtext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 196 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 532 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 76 "wizard_protocol_lexer.l"
BEGIN (COMMAND);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 77 "wizard_protocol_lexer.l"
{
	char *tmp;
	tmp = lexer_string ();
	g_assert (tmp != NULL && strlen (tmp) == 1);
	command = tmp[0];
	g_free (tmp);
	BEGIN (PARAMS);
}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 85 "wizard_protocol_lexer.l"
{
	char *params;
	params = lexer_string ();
	handle_command (command, params);
	g_free (params);
	BEGIN (INITIAL);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 92 "wizard_protocol_lexer.l"
{
	highlighting = TRUE;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 95 "wizard_protocol_lexer.l"
{
	highlighting = FALSE;
}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 98 "wizard_protocol_lexer.l"
warlock_bell ();
	YY_BREAK
case 7:
/* rule 7 can match eol */
YY_RULE_SETUP
#line 99 "wizard_protocol_lexer.l"
arrival_string();
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 100 "wizard_protocol_lexer.l"
output_string ();
	YY_BREAK
case 9:
/* rule 9 can match eol */
YY_RULE_SETUP
#line 101 "wizard_protocol_lexer.l"
eol_code ();
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 102 "wizard_protocol_lexer.l"
unhandled_character();
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 103 "wizard_protocol_lexer.l"
ECHO;
	YY_BREAK
#line 1086 "wizard_protocol_lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COMMAND):
case YY_STATE_EOF(PARAMS):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed wizardin at a new source and called
			 * wizardlex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = wizardin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( wizardwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * wizardtext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of wizardlex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					wizardrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			wizardrestart(wizardin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) wizardrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 196 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 196 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 195);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					wizardrestart(wizardin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( wizardwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve wizardtext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void wizardrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        wizardensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            wizard_create_buffer(wizardin,YY_BUF_SIZE );
	}

	wizard_init_buffer(YY_CURRENT_BUFFER,input_file );
	wizard_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void wizard_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		wizardpop_buffer_state();
	 *		wizardpush_buffer_state(new_buffer);
     */
	wizardensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	wizard_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (wizardwrap()) processing, but the only time this flag
	 * is looked at is after wizardwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void wizard_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	wizardin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE wizard_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) wizardalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in wizard_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) wizardalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in wizard_create_buffer()" );

	b->yy_is_our_buffer = 1;

	wizard_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with wizard_create_buffer()
 * 
 */
    void wizard_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		wizardfree((void *) b->yy_ch_buf  );

	wizardfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a wizardrestart() or at EOF.
 */
    static void wizard_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	wizard_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then wizard_init_buffer was _probably_
     * called from wizardrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void wizard_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		wizard_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void wizardpush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	wizardensure_buffer_stack();

	/* This block is copied from wizard_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from wizard_switch_to_buffer. */
	wizard_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void wizardpop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	wizard_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		wizard_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void wizardensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)wizardalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in wizardensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)wizardrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in wizardensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE wizard_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) wizardalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in wizard_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	wizard_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to wizardlex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       wizard_scan_bytes() instead.
 */
YY_BUFFER_STATE wizard_scan_string (yyconst char * yystr )
{
    
	return wizard_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to wizardlex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE wizard_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) wizardalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in wizard_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = wizard_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in wizard_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up wizardtext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		wizardtext[wizardleng] = (yy_hold_char); \
		(yy_c_buf_p) = wizardtext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		wizardleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int wizardget_lineno  (void)
{
        
    return wizardlineno;
}

/** Get the input stream.
 * 
 */
FILE *wizardget_in  (void)
{
        return wizardin;
}

/** Get the output stream.
 * 
 */
FILE *wizardget_out  (void)
{
        return wizardout;
}

/** Get the length of the current token.
 * 
 */
int wizardget_leng  (void)
{
        return wizardleng;
}

/** Get the current token.
 * 
 */

char *wizardget_text  (void)
{
        return wizardtext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void wizardset_lineno (int  line_number )
{
    
    wizardlineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see wizard_switch_to_buffer
 */
void wizardset_in (FILE *  in_str )
{
        wizardin = in_str ;
}

void wizardset_out (FILE *  out_str )
{
        wizardout = out_str ;
}

int wizardget_debug  (void)
{
        return wizard_flex_debug;
}

void wizardset_debug (int  bdebug )
{
        wizard_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from wizardlex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    wizardin = stdin;
    wizardout = stdout;
#else
    wizardin = (FILE *) 0;
    wizardout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * wizardlex_init()
     */
    return 0;
}

/* wizardlex_destroy is for both reentrant and non-reentrant scanners. */
int wizardlex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		wizard_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		wizardpop_buffer_state();
	}

	/* Destroy the stack itself. */
	wizardfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * wizardlex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *wizardalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *wizardrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void wizardfree (void * ptr )
{
	free( (char *) ptr );	/* see wizardrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 103 "wizard_protocol_lexer.l"


static char *
lexer_string (void)
{
        return g_strndup (wizardtext, wizardleng);
}

static void
unrecognized_command (int command)
{
        static GSList *list = NULL;
        GtkWidget *dialog;
        GtkWidget *parent;

        // Don't display a message if we already have
        if (g_slist_find (list, GINT_TO_POINTER (command)) != NULL) {
                return;
        }

        /* add the status to the list so we don't show it again */
        list = g_slist_append (list, GINT_TO_POINTER (command));

        /* display a warning */
        parent = glade_xml_get_widget (warlock_xml, "main_window");
        dialog = gtk_message_dialog_new (GTK_WINDOW (parent),
                        GTK_DIALOG_DESTROY_WITH_PARENT,
                        GTK_MESSAGE_ERROR, GTK_BUTTONS_CLOSE, 
                        "Got and unrecognized command character: %c\n"
                        "Please submit a bug report at http://sourceforge.net/tracker/?group_id=12587&atid=112587"
                        " or send an email to sproctor@gmail.com\n"
                        "Please let us know what you were doing when you got "
                        "this message and any other information that might "
                        "help us figure out what this comand character means.",
                        command);

        gtk_dialog_run (GTK_DIALOG (dialog));
        gtk_widget_destroy (dialog);
}

static void
handle_command (char command, char *params)
{
        int time;
	int len;

	/* TODO the following few lines should be moved into the lexer
	 *      eventually
	 */
	// change the trailing newline to a null
	len = strlen (params);
	if (len >= 1 && params[len - 1] == '\n') {
		params[len - 1] = '\0';
		if (len >= 2 && params[len - 2] == '\r') {
			params[len - 2] = '\0';
		}
	}

	switch (command) {
		case 'A': // initial time setting?
			break;
		case 'B': // character name, and a number (all 0's)
                        simu_connection_send (connection, "GOOD\n");
			break;
		case 'C': // server wants you to disconnect
                        debug ("got a message from the server telling us to "
                                        "quit\n");
                        quit = TRUE;
			break;
		case 'D': // seen at login - function unknown
			break;
		case 'F': // maybe to display pictures?
			break;
		case 'H': // room description to follow
			break;
		case 'I': // items/NPC's/characters to follow
			break;
                case 'J': // something to do with poison
                        break;
                case 'K': // like GSJ but for disease
                        break;
		case 'L': // start of a highlight
			highlighting = TRUE;
			break;
		case 'M': // end of a highlight
			highlighting = FALSE;
			break;
		case 'P': // player's status - see docs for details
			status_set (params);
			break;
		case 'Q': // gives us when the roundtime will end
                        time = atoi (g_strchomp (params));
                        if (time != 0) {
                                new_roundtime (time);
                        }
			break;
		case 'V': // seen at login - function unknown
			break;
		case 'W': // sent when wounds change
			break;
		case 'X': // the number of hit points you have
			break;
		case 'Y': // the number of spirit points you have
			break;
		case 'Z': // the number of mana points you have
			break;
                case 'a': //wounds/severity
                        break;
		case 'b': // scars
			break;
		case 'c': // familiar start
			familiar = TRUE;
			break;
		case 'd': // familiar end
			familiar = FALSE;
			break;
		case 'e': // familiar start (again?)
			familiar= TRUE;
			break;
		case 'f': // familiar end (again?)
			familiar = FALSE;
			break;
		case 'g': // current stance - see docs for details
			break;
		case 'j': // directions you can go - see docs for details
			compass_set_directions (params);
			break;
		case 'l': // left hand contents
			hand_set_contents (LEFT_HAND, parse_hand (params));
			break;
		case 'm': // right hand contents
			hand_set_contents (RIGHT_HAND, parse_hand (params));
			break;
		case 'n': // gives us the spell being prepared (not DR)
			break;
		case 'o': // marks the start of the room description
			  // done waiting in move.
			  // TODO setup hooks for these so we don't have this
			  //      kind of code in this file
			script_moved ();
#ifdef CONFIG_SPIDERMONKEY
			js_script_moved ();
#endif
			room_title = TRUE;
			break;
		case 'p': // marks then end of the room description
			room_title = FALSE;
			break;
		case 'q': // gives us the current game time and signifies that
			  // we should give a status prompt
                        time = atoi (g_strchomp (params));
                        if (time != 0) {
                                warlock_set_time (time);
                        }
			do_prompt ();
			break;
                case 'r': // I have no idea what this command does
                        break;
		case 't': // signifies contents of the hands have changed
			break;
		case 'w':
			if (strcmp (g_strchomp (params), "00003") == 0) {
				death = TRUE;
			} else if (strcmp (g_strchomp (params), "00004") == 0) {
				death = FALSE;
			} else {
                                debug ("unsupported GSw command: %s\n",
                                                g_strchomp (params));
                        }
			break;
		default:
			debug ("unsupported command: %c\n", command);
                        unrecognized_command (command);
                        break;
	}
}

// removes duplicate spaces in a string
static void
compress_whitespace (char *str)
{
	char *ptr;

        for(ptr = str; str[0] != '\0'; str++) {
                if (!isspace (str[0]) || !isspace (str[1])) {
                        ptr[0] = str[0];
                        ptr++;
                }
        }
        ptr[0] = '\0';
}

// follows the simu protocol for what a hand contains
// check docs/SIMU-PROTOCOL for more info
static char *
parse_hand (char *str)
{
	char temp[16];
        char *new_string;
        int i;

        debug ("hand string length: %ui\n", (unsigned int) strlen (str));
        g_assert (strlen (str) == 45);

        new_string = g_new (char, 48);
        new_string[0] = '\0';
        for (i = 0; i < 3; i++) {
                g_strlcpy (temp, str + i * 15, 16);
                g_strlcat (new_string, g_strchomp (temp), 48);
                g_strlcat (new_string, " ", 48);
        }

        compress_whitespace (new_string);

        return new_string;
}

static void
arrival_string (void)
{
	char *string;
	WString *w_string;

	string = g_strndup (wizardtext, wizardleng);
	w_string = w_string_new (g_strchomp (string));
	warlock_view_append ("arrival", w_string);
	w_string_free (w_string, TRUE);
	warlock_view_end_line ("arrival");
}

static void
output_string (void)
{
	WString *string = w_string_new_len (wizardtext, wizardleng);

	if (highlighting) {
		w_string_add_tag (string, MONSTER_TAG, 0, -1);
	}

	if (room_title) {
		w_string_add_tag (string, TITLE_TAG, 0, -1);
	}

	if (familiar) {
		warlock_view_append ("familiar", string);
	} else if (death) {
		warlock_view_append ("death", string);
	} else {
		warlock_view_append (NULL, string);
	}

	w_string_free (string, TRUE);
}

static void
eol_code (void)
{
	if (familiar) {
		warlock_view_end_line ("familiar");
	} else if (death) {
		warlock_view_end_line ("death");
	} else {
		warlock_view_end_line (NULL);
	}
}

int
wizardparse (void)
{
	quit = FALSE;

	for (;;) {
                int val;

                val = wizardlex ();
		if (val == 0) {
			return 0;
		}

		if (quit) {
			return 1;
		}
	}	
}

static void
unhandled_character (void)
{
	WString *string = w_string_new_len (wizardtext, wizardleng);
	debug ("Unhandled character %s\n", string->string->str);
}

